* Table of Contents :TOC_3:
  - [[#introduction][Introduction]]
  - [[#installation][Installation]]
  - [[#usage][Usage]]
  - [[#license][License]]

** Introduction
 Roam-block is an all-purpose block references and block embed implement in emacs.

** Installation

 Firstly, install the dependencies:

 - [[https://www.sqlite.org/index.html][sqlite3]] cli
 - [[https://github.com/skeeto/emacsql][emacsql]] package
 - [[https://github.com/cireu/emacsql-sqlite3][emacsql-sqlite3]] package

 Then, clone roam-block repo to your local directory and add the following codes to your emacs configuration:

 #+BEGIN_SRC emacs-lisp
 (add-to-list 'load-path "path/to/roam-block/")
 (require 'roam-block)
 (setq 'roam-block-home '("~/roam-block/"))
 (roam-block-mode 1)
 (define-key roam-block-mode-map (kbd "C-c b c") #'roam-block-ref-copy)
 (define-key roam-block-mode-map (kbd "C-c b e") #'roam-block-ref-edit)
 #+END_SRC

 If you prefer 'use-package', use the following codes:

 #+BEGIN_SRC emacs-lisp
 (use-package roam-block
   :load-path "path/to/roam-block/"
   :hook (after-init . roam-block-mode)
   :init (setq roam-block-home '("~/roam-block/"))
   :bind
   (:map roam-block-mode-map
         (("C-c b c" . roam-block-ref-copy)
          ("C-c b e" . roam-block-ref-edit))))
 #+END_SRC

** Usage
 
   =roam-block-ref-copy=\\
   Copy the ref of current block or blocks in an active region, then press =C-y= to paste the ref at where you want to refer the blocks.

   =roam-block-ref-edit=\\
   By default, the block ref is read only. Use this command to edit the displayed content in an edit buffer.

** License
   Copyright © Kinney Zhang and contributors. Distributed under the [[./LICENSE][GPL v3.0]].

