#+TITLE: Block-ref

* Introduction
Block-ref is used to implement versatile block references and block embed between different types of files. It means, you can insert block references in files without caring about the filename extentions due to the technique of implement.

* Installation

Firstly, install the dependencies: [[https://github.com/skeeto/emacsql][emacsql]] and [[https://github.com/cireu/emacsql-sqlite3][emacsql-sqlite3]].

Then, clone block-ref repo to your local directory and add the following codes to your emacs configuration:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/path/to/block-ref")
(require 'block-ref)
(setq block-ref-directory "~/block-ref/")
(define-key block-ref-mode-map (kbd "C-c b c") #'block-ref-copy-ref)
(define-key block-ref-mode-map (kbd "C-c b e") #'block-ref-edit-block)
(block-ref-mode 1)
#+END_SRC

If you prefer 'use-package', use the following codes:

#+BEGIN_SRC emacs-lisp
(use-package block-ref
  :load-path "/path/to/block-ref"
  :init (setq block-ref-directory "~/block-ref/")
  :bind (:map block-ref-mode-map
              (("C-c b c" . block-ref-copy-ref)
               ("C-c b e" . block-ref-edit-block)))
  :config (block-ref-mode 1))
#+END_SRC

* Usage
 
 Use command =block-ref-copy-ref= to copy the ref link of current block or blocks in an active region, then press <kbd>C-y<kbd> to paste the block-ref link at where you want to refer the blocks.

 The block references is read only by default. Use =block-ref-edit-block= to edit it in block-ref-edit buffer.

* License
  Copyright © Kinney Zhang and contributors. Distributed under the [[./LICENSE][GPL v3.0]].

